apiVersion: apps/v1
kind: Deployment
metadata:
 name: fizzbuzzcomtestesdeploy
spec:
 selector:
   matchLabels:
     app: fizzbuzz
 replicas: 2
 template:
   metadata:
     labels:
       app: fizzbuzz
   spec:
     containers:
     - name: fizzbuzz
       image: dannxp/fizzbuzzcomtestes
       ports:
       - containerPort: 80